### ISSUE TITLE
Possible to set the intercept to 0

### ISSUE THREAD

**Issue by snowpong** [YaohuiZeng/biglasso#19] opened 2018-11-20 13:33 UTC
Hi.

Thanks for making biglasso, it works well with bigmemory and memory-mapped files.

Is there a way, or hack, to set the intercept to 0? In `glmnet` you can set `intercept=FALSE` and the intercept(s) are set to zero.

**Comment by bsytffgj** [comment] 2022-09-20 12:18
Was the problem solved or not? I'm eager for the answer too.

**Comment by snowpong** [comment] 2022-09-20 14:45
@bsytffgj I never found a solution. But worked around / didn't need a solution for it in the end.

**Comment by pbreheny** [comment] 2022-09-22 15:53
Duplicate of #37

**Closed by pbreheny** 2022-09-22 15:53 UTC
